[2020-04-29 00:29:37,052][ERROR][logg.add_row_to_products:296] No search   ()
Traceback (most recent call last):
  File "mysqlCon.py", line 272, in add_row_to_products
    con.checkbarcode(barcode)
NameError: name 'con' is not defined
