[2020-04-29 15:24:12,103][ERROR][logg.listProduct:310] no row   ()
Traceback (most recent call last):
  File "mysqlCon.py", line 297, in listProduct
    cursor.execute(sql0, (startLimit,countProduct))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: %d format: a number is required, not str
[2020-04-29 15:24:12,104][ERROR][logg.main:448] Error connect to Mysql   ()
Traceback (most recent call last):
  File "mysqlCon.py", line 297, in listProduct
    cursor.execute(sql0, (startLimit,countProduct))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: %d format: a number is required, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mysqlCon.py", line 444, in main
    print(con.listProduct('0','8'))
  File "mysqlCon.py", line 311, in listProduct
    raise Exception("no row")
Exception: no row
